# Netlify Configuration for Hackerspace Mumbai Blog
# Production-ready configuration with security, performance, and reliability features

[build]
  # Build settings
  publish = "dist"
  functions = "netlify/functions"
  command = "pnpm build"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  # Enable pnpm
  NPM_FLAGS = "--version"

# Function configuration
[functions]
  # Global function settings
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
  
  # Enhanced function settings for better performance and monitoring
  [functions.newsletter]
    # Specific settings for newsletter function
    timeout = 30
    memory = 256
    # Enable detailed logging
    environment = { LOG_LEVEL = "info" }

# Redirects for API endpoints
[[redirects]]
  from = "/api/newsletter"
  to = "/.netlify/functions/newsletter"
  status = 200
  force = true

[[redirects]]
  from = "/subscribe"
  to = "/.netlify/functions/newsletter"
  status = 200
  force = true

# Health check endpoint
[[redirects]]
  from = "/api/newsletter/health"
  to = "/.netlify/functions/newsletter-health"
  status = 200

[[redirects]]
  from = "/health/newsletter"
  to = "/.netlify/functions/newsletter-health"
  status = 200

# Blog post redirects (for SEO)
[[redirects]]
  from = "/posts/*"
  to = "/blog/:splat"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    # API-specific headers
    Access-Control-Allow-Origin = "https://hackmum.in"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"
    # Prevent caching of dynamic API responses
    Cache-Control = "no-store"
    
    # Security for API endpoints
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
    # Rate limiting headers (informational)
    X-RateLimit-Limit = "5"
    X-RateLimit-Window = "900"
    
    # Additional security headers for API endpoints
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
  Content-Security-Policy = "default-src 'none'; frame-ancestors 'none';"

# Enhanced headers for newsletter function specifically
[[headers]]
  for = "/.netlify/functions/newsletter"
  [headers.values]
    # Newsletter-specific CORS
    Access-Control-Allow-Origin = "https://hackmum.in"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Max-Age = "86400"
    
    # Enhanced security
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
    # Rate limiting information
    X-RateLimit-Limit = "5"
    X-RateLimit-Window = "900"
    X-RateLimit-Remaining = "5"
    
    # Cache control for API responses
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Environment-specific configurations
[context.production]
  [context.production.environment]
    NODE_ENV = "production"
    CORS_ORIGIN = "https://hackmum.in"
    LOG_LEVEL = "info"
    # Enable enhanced monitoring in production
    ENABLE_MONITORING = "true"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "preview"
    CORS_ORIGIN = "*"
    LOG_LEVEL = "debug"
    ENABLE_MONITORING = "false"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    CORS_ORIGIN = "*"
    LOG_LEVEL = "debug"
    ENABLE_MONITORING = "false"

# Form handling (backup for newsletter if needed)
[forms]
  # Enable Netlify Forms as fallback
  
# Edge functions (if needed in future)
# [[edge_functions]]
#   function = "newsletter-edge"
#   path = "/api/newsletter-edge"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Development settings
[dev]
  framework = "#auto"
  targetPort = 4321
  port = 8888
  publish = "dist"
  autoLaunch = false